version: '3'
services: 
  api-config-service:
    build: .
    image: api-config-service
    ports: 
      - 80:80
    environment: 
      MONGO_URL: mongodb
      MONGO_PORT: 27017
    links:
      - mongodb

  mongodb:
    image: mongo:3.5
    ports: 
      - 27017:27017